# Generated by Django 4.1.5 on 2023-03-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cartId',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='productId',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customerId',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
